apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: greet-me
    path: patch-image.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: greet-me-ingress
    path: patch-ingress.yaml
