apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yml
  - ingress.yaml
  # - secrets.yaml

namespace: prod

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: greet-me
    path: patch-image.yaml

