apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-me
  labels:
    app: greet-me
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: greet-me
  template:
    metadata:
      labels:
        app: greet-me
    spec:
      containers:
      - name: greet-me
        image: ghcr.io/veerendra2/greet-me-flask-app/greet-me
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
          limits:
            cpu: 100m
            memory: 100Mi
      - name: nginx
        image: nginx:1.24.0-alpine
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      imagePullSecrets:
        - name: regcred
