apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: apps
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  _;

        location / {
            proxy_pass http://127.0.0.1:8000/;
        }
    }
