apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: apps
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass http://localhost:8000;
        }
    }
