name: CI/CD

on:
  pull_request_review:
    types:
      - submitted
    paths:
      - "src/**"
      - "kubernetes/**"

jobs:
  detect_changes:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      src: ${{ steps.filter.outputs.src }}
      kubernetes: ${{ steps.filter.outputs.kubernetes }}

    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'
          kubernetes:
            - 'kubernetes/**'

  build_and_push:
    needs: [detect_changes]
    if: ${{ needs.detect_changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest

    outputs:
      sha_short : ${{ steps.vars.outputs.sha_short }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push docker image(linux/arm64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/greet-me-flask-app/greet-me:${{ steps.vars.outputs.sha_short }}
          platforms: linux/arm64,linux/amd64

  deploy_staging:
    needs: [detect_changes, build_and_push]
    if: |
      always() &&
      (needs.build_and_push.result == 'success' || needs.build_and_push.result == 'skipped')
    runs-on: self-hosted
    environment: stage

    outputs:
      sha_short : ${{ needs.build_and_push.outputs.sha_short }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start minikube(staging)
        uses: medyagh/setup-minikube@master

      - name: Test minikube(staging)
        run: kubectl cluster-info

      - name: Update docker image label
        if: needs.build_and_push.result == 'success'
        run: |
          cd kubernetes/stages/staging
          sed -i "s/greet-me:.*/greet-me:${{ needs.build_and_push.outputs.sha_short }}/g" patch-image.yaml
          cat patch-image.yaml

      - name: Deploy to Staging
        run: |
          kustomize build kubernetes/stages/staging/ | kubectl apply -f -
          sleep 10

      - name: Test service URLs
        run: |
          minikube service list
          minikube service example --url
          echo "------------------opening the service------------------"
          curl $(minikube service example --url)

      - name: Commit changes
        if: needs.build_and_push.result == 'success'
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update docker image tag"
            git push origin HEAD:${{ github.head_ref }}
          fi

  deploy_prod:
    needs: [deploy_staging]
    if: |
      always() &&
      (needs.deploy_staging.result == 'success')
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start minikube(prod)
        uses: medyagh/setup-minikube@master

      - name: Test minikube(prod)
        run: kubectl cluster-info

      - name: Update docker image label
        if: needs.build_and_push.result == 'success'
        run: |
          git pull origin ${{ github.head_ref }}
          cd kubernetes/stages/prod
          sed -i "s/greet-me:.*/greet-me:${{ needs.deploy_staging.outputs.sha_short }}/g" patch-image.yaml
          cat patch-image.yaml

      - name: Deploy to Prod
        run: |
          kustomize build kubernetes/stages/prod/ | kubectl apply -f -
          sleep 10

      - name: Test service URLs
        run: |
          minikube service list
          minikube service example --url
          curl $(minikube service example --url)

      - name: Commit changes
        if: needs.build_and_push.result == 'success'
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update docker image tag"
            git push origin HEAD:${{ github.head_ref }}
          fi
