name: Deploy Only

on:
  # workflow_dispatch:
  #   inputs:
  #     blog:
  #       description: "Run Tests"
  #       required: true
  #       default: "yes"

  pull_request:
    paths:
      - "kubernetes/base/**"
      - "kubernetes/stages/**"

jobs:
  lint_test:
    uses: ./.github/workflows/lint-and-test.yaml

  deploy_staging:
    needs: [lint_test]
    runs-on: self-hosted
    environment: stage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          kustomize build kubernetes/stages/staging/ | kubectl apply -f -
          sleep 10

  deploy_prod:
    needs: [deploy_staging]
    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Prod
        run: |
          kustomize build kubernetes/stages/prod/ | kubectl apply -f -
          sleep 10
