name: Test Workflow on Self-Hosted Runners

on:
  workflow_dispatch:
    inputs:
      blog:
        description: "Run Tests"
        required: true
        default: "yes"
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deploy script on self-hosted runner
        run: |
          kubectl get pods -n apps